server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/customer_db
spring.datasource.username=${DB_USER:customer}
spring.datasource.password=${DB_PASSWORD:customer}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true