spring.application.name=customer-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

jwt.private-key=classpath:certs/private.pem
jwt.public-key=classpath:certs/public.pem
jwt.expiration-seconds=3600